CREATE TABLE "competitor" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "competitor_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"state" varchar(32) DEFAULT 'active' NOT NULL,
	"thumbnail" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "competitor_products" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "competitor_products_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"product_id" integer NOT NULL,
	"competitor_id" integer,
	"title" text NOT NULL,
	"external_id" varchar(255),
	"product_link" text NOT NULL,
	"source" varchar(255) NOT NULL,
	"currency" varchar(16),
	"thumbnail" text,
	"tag" text,
	"google_position" integer,
	"status" varchar(32) DEFAULT 'suggested' NOT NULL,
	"country" varchar(8),
	"rating" numeric(3, 1),
	"review_count" integer,
	"shipping_raw" varchar(64),
	"shipping_extracted" numeric(12, 4),
	"extracted_old_price" numeric(12, 4),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "customer_addresses" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "customer_addresses_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"customer_id" integer NOT NULL,
	"shopify_address_id" bigint,
	"address_name" varchar(255),
	"company" varchar(255),
	"address1" varchar(255),
	"address2" varchar(255),
	"city" varchar(128),
	"province" varchar(128),
	"country" varchar(128),
	"zip" varchar(32),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "customers" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "customers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"shopify_customer_id" bigint NOT NULL,
	"email" varchar(255) NOT NULL,
	"first_name" varchar(255) NOT NULL,
	"last_name" varchar(255) NOT NULL,
	"phone" varchar(64),
	"state" varchar(32),
	"currency" varchar(16),
	"verified_email" boolean,
	"customer_tags" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "order_items" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "order_items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"order_id" integer NOT NULL,
	"product_id" integer,
	"shopify_line_item_id" bigint NOT NULL,
	"shopify_product_id" bigint,
	"shopify_variant_id" bigint,
	"title" varchar(500) NOT NULL,
	"variant_title" varchar(255),
	"sku" varchar(255),
	"quantity" integer NOT NULL,
	"current_quantity" integer,
	"unit_price" numeric(12, 4),
	"total_discount" numeric(12, 4),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "orders" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "orders_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"shopify_order_id" bigint NOT NULL,
	"customer_id" integer,
	"order_number" varchar(64) NOT NULL,
	"email" varchar(255),
	"financial_status" varchar(64),
	"fulfillment_status" varchar(64),
	"currency" varchar(16),
	"subtotal_price" numeric(12, 4),
	"total_price" numeric(12, 4),
	"total_tax" numeric(12, 4),
	"total_shipping" numeric(12, 4),
	"total_discounts" numeric(12, 4),
	"source_name" varchar(255),
	"referring_site" text,
	"landing_site" text,
	"processed_at" timestamp with time zone,
	"total_weight" numeric(10, 3),
	"cancelled_at" timestamp with time zone,
	"shopify_created_at" timestamp with time zone,
	"shopify_updated_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "price_history" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "price_history_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"competitor_product_id" integer NOT NULL,
	"price" varchar(64),
	"extracted_price" numeric(12, 4) NOT NULL,
	"captured_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "price_insights" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "price_insights_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"product_id" integer NOT NULL,
	"min_price" numeric(12, 4) NOT NULL,
	"max_price" numeric(12, 4) NOT NULL,
	"summary" text NOT NULL,
	"market_position" varchar(32) NOT NULL,
	"captured_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "product_ai_reports" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "product_ai_reports_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"product_id" integer NOT NULL,
	"status" varchar(20) NOT NULL,
	"model" varchar(100) NOT NULL,
	"report_types" jsonb NOT NULL,
	"input_hash" varchar(64) NOT NULL,
	"input_snapshot" jsonb,
	"output" jsonb,
	"error_message" text,
	"generated_by" varchar(255),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"completed_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "product_images" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "product_images_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"product_id" integer NOT NULL,
	"external_id" bigint NOT NULL,
	"position" integer NOT NULL,
	"alt" varchar(512) NOT NULL,
	"width" integer,
	"height" integer,
	"src" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "products" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "products_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"external_id" bigint NOT NULL,
	"status" varchar(32) DEFAULT 'draft' NOT NULL,
	"thumbnail" text,
	"price" numeric(12, 4),
	"cost" numeric(12, 4),
	"currency" varchar(16),
	"handle" varchar(500),
	"title" varchar(500),
	"brand" varchar(255),
	"inventory_quantity" integer,
	"weight_unit" varchar(16),
	"weight" numeric(10, 3),
	"sku" varchar(255),
	"tags" text,
	"description" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "competitor_products" ADD CONSTRAINT "competitor_products_product_id_products_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."products"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "competitor_products" ADD CONSTRAINT "competitor_products_competitor_id_competitor_id_fk" FOREIGN KEY ("competitor_id") REFERENCES "public"."competitor"("id") ON DELETE restrict ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "customer_addresses" ADD CONSTRAINT "customer_addresses_customer_id_customers_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "order_items" ADD CONSTRAINT "order_items_order_id_orders_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "order_items" ADD CONSTRAINT "order_items_product_id_products_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."products"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "orders" ADD CONSTRAINT "orders_customer_id_customers_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "price_history" ADD CONSTRAINT "price_history_competitor_product_id_competitor_products_id_fk" FOREIGN KEY ("competitor_product_id") REFERENCES "public"."competitor_products"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "price_insights" ADD CONSTRAINT "price_insights_product_id_products_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."products"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "product_ai_reports" ADD CONSTRAINT "product_ai_reports_product_id_products_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."products"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "product_images" ADD CONSTRAINT "product_images_product_id_products_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."products"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
CREATE UNIQUE INDEX "competitor_name_unique" ON "competitor" USING btree ("name");--> statement-breakpoint
CREATE INDEX "competitor_products_product_id_idx" ON "competitor_products" USING btree ("product_id");--> statement-breakpoint
CREATE INDEX "competitor_products_competitor_id_idx" ON "competitor_products" USING btree ("competitor_id");--> statement-breakpoint
CREATE UNIQUE INDEX "competitor_products_listing_unique" ON "competitor_products" USING btree ("product_id","competitor_id","external_id");--> statement-breakpoint
CREATE UNIQUE INDEX "customer_addresses_shopify_address_id_unique" ON "customer_addresses" USING btree ("shopify_address_id");--> statement-breakpoint
CREATE INDEX "customer_addresses_customer_id_idx" ON "customer_addresses" USING btree ("customer_id");--> statement-breakpoint
CREATE UNIQUE INDEX "customers_shopify_customer_id_unique" ON "customers" USING btree ("shopify_customer_id");--> statement-breakpoint
CREATE UNIQUE INDEX "order_items_shopify_line_item_id_unique" ON "order_items" USING btree ("shopify_line_item_id");--> statement-breakpoint
CREATE INDEX "order_items_order_id_idx" ON "order_items" USING btree ("order_id");--> statement-breakpoint
CREATE INDEX "order_items_product_id_idx" ON "order_items" USING btree ("product_id");--> statement-breakpoint
CREATE UNIQUE INDEX "orders_shopify_order_id_unique" ON "orders" USING btree ("shopify_order_id");--> statement-breakpoint
CREATE INDEX "orders_customer_id_idx" ON "orders" USING btree ("customer_id");--> statement-breakpoint
CREATE INDEX "orders_shopify_updated_at_idx" ON "orders" USING btree ("shopify_updated_at");--> statement-breakpoint
CREATE INDEX "price_history_competitor_product_id_idx" ON "price_history" USING btree ("competitor_product_id");--> statement-breakpoint
CREATE INDEX "price_insights_product_id_idx" ON "price_insights" USING btree ("product_id");--> statement-breakpoint
CREATE INDEX "idx_product_ai_reports_product_created" ON "product_ai_reports" USING btree ("product_id","created_at");--> statement-breakpoint
CREATE INDEX "idx_product_ai_reports_product_status" ON "product_ai_reports" USING btree ("product_id","status");--> statement-breakpoint
CREATE INDEX "idx_product_ai_reports_input_hash" ON "product_ai_reports" USING btree ("input_hash");--> statement-breakpoint
CREATE UNIQUE INDEX "product_images_product_external_unique" ON "product_images" USING btree ("product_id","external_id");--> statement-breakpoint
CREATE INDEX "products_external_id_idx" ON "products" USING btree ("external_id");