apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: price-insight
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: price-insight-ksa
      containers:
        - name: backend
          image: australia-southeast1-docker.pkg.dev/wd-tools/price-insight/price-insight-backend:latest
          ports:
            - containerPort: 4000
          envFrom:
            - secretRef:
                name: backend-secrets
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "4000"
            - name: APP_URL
              value: "https://qweyha520.bar"
          readinessProbe:
            httpGet:
              path: /api/health
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
