apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: price-insight
  annotations:
    cloud.google.com/backend-config: '{"default": "backend-config"}'
spec:
  selector:
    app: backend
  ports:
    - port: 4000
      targetPort: 4000
