apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: price-insight
  annotations:
    cloud.google.com/backend-config: '{"default": "frontend-config"}'
spec:
  selector:
    app: frontend
  ports:
    - port: 3000
      targetPort: 3000
