apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: price-insight
  namespace: price-insight
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "price-insight-ip"
    networking.gke.io/managed-certificates: "price-insight-cert"
spec:
  rules:
    - host: qweyha520.bar
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 4000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 3000
