-- Price Insight: PostgreSQL / Supabase schema
-- Converted from Cloud_SQL_Export_2026-08-11 (18_33_20).sql
-- Application schema only. Existing MySQL Drizzle migration history is intentionally excluded.

begin;

create table public.competitor (
  id integer generated by default as identity primary key,
  name varchar(255) not null,
  state varchar(32) not null default 'active',
  thumbnail text,
  created_at timestamptz not null default now(),
  constraint competitor_name_unique unique (name)
);

create table public.products (
  id integer generated by default as identity primary key,
  external_id bigint not null,
  status varchar(32) not null default 'draft',
  thumbnail text,
  price numeric(12,4),
  currency varchar(16),
  handle varchar(500),
  title varchar(500),
  brand varchar(255),
  inventory_quantity integer,
  weight_unit varchar(16),
  weight numeric(10,3),
  sku varchar(255),
  tags text,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  cost numeric(12,4)
);
create index products_external_id_idx on public.products (external_id);

create table public.customers (
  id integer generated by default as identity primary key,
  shopify_customer_id bigint not null,
  email varchar(255) not null,
  first_name varchar(255) not null,
  last_name varchar(255) not null,
  phone varchar(64),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  state varchar(32),
  currency varchar(16),
  verified_email boolean,
  customer_tags text,
  constraint customers_shopify_customer_id_unique unique (shopify_customer_id)
);

create table public.competitor_products (
  id integer generated by default as identity primary key,
  product_id integer not null,
  competitor_id integer,
  title text not null,
  external_id varchar(255),
  product_link text not null,
  source varchar(255) not null,
  currency varchar(16),
  thumbnail text,
  tag text,
  google_position integer,
  created_at timestamptz not null default now(),
  status varchar(32) not null default 'suggested',
  country varchar(8),
  rating numeric(3,1),
  review_count integer,
  shipping_raw varchar(64),
  shipping_extracted numeric(12,4),
  extracted_old_price numeric(12,4),
  constraint competitor_products_product_id_products_id_fk
    foreign key (product_id) references public.products(id) on delete cascade on update cascade,
  constraint competitor_products_competitor_id_competitor_id_fk
    foreign key (competitor_id) references public.competitor(id) on delete restrict on update cascade
);
create index competitor_products_product_id_idx on public.competitor_products (product_id);
create index competitor_products_competitor_id_idx on public.competitor_products (competitor_id);

create table public.customer_addresses (
  id integer generated by default as identity primary key,
  customer_id integer not null,
  shopify_address_id bigint,
  address1 varchar(255),
  address2 varchar(255),
  city varchar(128),
  province varchar(128),
  country varchar(128),
  zip varchar(32),
  created_at timestamptz not null default now(),
  address_name varchar(255),
  company varchar(255),
  constraint customer_addresses_shopify_address_id_unique unique (shopify_address_id),
  constraint customer_addresses_customer_id_customers_id_fk
    foreign key (customer_id) references public.customers(id) on delete cascade on update cascade
);
create index customer_addresses_customer_id_idx on public.customer_addresses (customer_id);

create table public.orders (
  id integer generated by default as identity primary key,
  shopify_order_id bigint not null,
  customer_id integer,
  order_number varchar(64) not null,
  email varchar(255),
  financial_status varchar(64),
  fulfillment_status varchar(64),
  currency varchar(16),
  subtotal_price numeric(12,4),
  total_price numeric(12,4),
  total_tax numeric(12,4),
  total_shipping numeric(12,4),
  total_discounts numeric(12,4),
  cancelled_at timestamptz,
  shopify_created_at timestamptz,
  shopify_updated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  source_name varchar(255),
  referring_site text,
  landing_site text,
  processed_at timestamptz,
  total_weight numeric(10,3),
  constraint orders_shopify_order_id_unique unique (shopify_order_id),
  constraint orders_customer_id_customers_id_fk
    foreign key (customer_id) references public.customers(id) on delete set null on update cascade
);
create index orders_customer_id_idx on public.orders (customer_id);
create index orders_shopify_updated_at_idx on public.orders (shopify_updated_at);

create table public.order_items (
  id integer generated by default as identity primary key,
  order_id integer not null,
  product_id integer,
  shopify_line_item_id bigint not null,
  shopify_product_id bigint,
  shopify_variant_id bigint,
  title varchar(500) not null,
  variant_title varchar(255),
  sku varchar(255),
  quantity integer not null,
  unit_price numeric(12,4),
  total_discount numeric(12,4),
  created_at timestamptz not null default now(),
  current_quantity integer,
  constraint order_items_shopify_line_item_id_unique unique (shopify_line_item_id),
  constraint order_items_order_id_orders_id_fk
    foreign key (order_id) references public.orders(id) on delete cascade on update cascade,
  constraint order_items_product_id_products_id_fk
    foreign key (product_id) references public.products(id) on delete set null on update cascade
);
create index order_items_order_id_idx on public.order_items (order_id);
create index order_items_product_id_idx on public.order_items (product_id);

create table public.price_history (
  id integer generated by default as identity primary key,
  competitor_product_id integer not null,
  price varchar(64),
  extracted_price numeric(12,4) not null,
  captured_at timestamptz not null default now(),
  constraint price_history_competitor_product_id_competitor_products_id_fk
    foreign key (competitor_product_id) references public.competitor_products(id) on delete cascade on update cascade
);
create index price_history_competitor_product_id_idx on public.price_history (competitor_product_id);

create table public.price_insights (
  id integer generated by default as identity primary key,
  product_id integer not null,
  min_price numeric(12,4) not null,
  max_price numeric(12,4) not null,
  summary text not null,
  market_position varchar(32) not null,
  captured_at timestamptz not null default now(),
  constraint price_insights_product_id_products_id_fk
    foreign key (product_id) references public.products(id) on delete cascade on update cascade
);
create index price_insights_product_id_idx on public.price_insights (product_id);

create table public.product_ai_reports (
  id integer generated by default as identity primary key,
  product_id integer not null,
  status varchar(20) not null,
  model varchar(100) not null,
  report_types jsonb not null,
  input_hash varchar(64) not null,
  input_snapshot jsonb,
  output jsonb,
  error_message text,
  generated_by varchar(255),
  created_at timestamptz not null default now(),
  completed_at timestamptz,
  constraint product_ai_reports_product_id_products_id_fk
    foreign key (product_id) references public.products(id) on delete cascade on update cascade
);
create index idx_product_ai_reports_product_created on public.product_ai_reports (product_id, created_at);
create index idx_product_ai_reports_product_status on public.product_ai_reports (product_id, status);
create index idx_product_ai_reports_input_hash on public.product_ai_reports (input_hash);

create table public.product_images (
  id integer generated by default as identity primary key,
  product_id integer not null,
  external_id bigint not null,
  position integer not null,
  alt varchar(512) not null,
  width integer,
  height integer,
  src text not null,
  constraint product_images_product_external_unique unique (product_id, external_id),
  constraint product_images_product_id_products_id_fk
    foreign key (product_id) references public.products(id) on delete cascade on update cascade
);

-- MySQL's ON UPDATE CURRENT_TIMESTAMP behavior for updated_at columns.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger products_set_updated_at
before update on public.products
for each row execute function public.set_updated_at();

create trigger customers_set_updated_at
before update on public.customers
for each row execute function public.set_updated_at();

create trigger orders_set_updated_at
before update on public.orders
for each row execute function public.set_updated_at();

commit;
